### ISSUE TITLE
What is the status of this plugin?

### ISSUE THREAD

**Issue by bramley** [phpList/phplist-plugin-restapi#12]
I might be missing something obvious but the plugin appears to have changed from something that worked reasonably well to a work in progress that cannot be used - it cannot be installed through phplist and then looking at the code seems to have partly-completed changes.

**Comment by michield** [comment]
yes, there is now a dependency on the phpList4 classes. It's not as simple as other plugins to download the zip from Github. Instructions on this will follow soon.

**Comment by michield** [comment]
Hmm, it's not trivial to get it back into working order. I will branch the old code, to avoid temporary regression

**Comment by samtuke** [comment]
Thanks @michield, sorry I hadn't intended that it appear as an available plugin just yet. The automated plugin publication mechanism is efficient indeed :)

**Comment by bramley** [comment]
Presumably the "stable" branch is now the one to use, so closing.
