### ISSUE TITLE
Send confirmation mail via API?

### ISSUE THREAD

**Issue by alexdahlem** [phpList/phplist-plugin-restapi#14]
Hello!

First of all thanks for your great work!
I am implementing PHPList for our company and we want to use the Rest API for different pages.
Is it possible to send out the standard confirmation mail the User added via subscriberAdd? I added the subscriber with confirmed = 0 but no mail was sent out.

Thanks a lot!

Alex

**Comment by michield** [comment]
yes, that's a good idea. Maybe with a flag or a config.

**Comment by michield** [comment]
the latest version of the plugin in the master branch now has a "subscribe" method which does that. If you can try it and comment, that would be great.

**Comment by michield** [comment]
https://github.com/phpList/phplist-plugin-restapi/blob/master/tests/phpunit/restapi.php#L366
