### ISSUE TITLE
Still got the UTF-8 Problem (when I run the campaignsGet())

### ISSUE THREAD

**Issue by zx1986** [phpList/phplist-plugin-restapi#21]
Here is what I got:
```
stdClass Object
(
    [status] => success
    [type] => Campaigns
    [data] => Array
        (
            [0] => stdClass Object
                (
                    [id] => 2
                    [subject] => Happy Birthday
                    [fromfield] => noreply@my.com
                    [tofield] => 
                    [replyto] => 
                    [message] => ?????
?????
?????
?????
```

phplist, version 3.2.3 
RESTAPI version 3

**Comment by zx1986** [comment]
I added ```$dbh->exec("set names utf8");``` in PDO, and got:
```
    [message] => çæ¥å¿«æ¨ï¼
çæ¥å¿«æ¨ï¼
çæ¥å¿«æ¨ï¼
çæ¥å¿«æ¨ï¼
```

**Comment by michield** [comment]
is your database UTF-8 enabled?

**Comment by michield** [comment]
Yes, I can replicate this issue. I will see if I can do something about it

**Comment by michield** [comment]
Remove the "utf8_encode" on this line, and it should work.

https://github.com/phpList/phplist-plugin-restapi/blob/master/plugins/restapi/includes/response.php#L69

Change the line to 
```
                $result[$key] = $value;
```

**Comment by michield** [comment]
https://github.com/michield/phplist-plugin-restapi/commit/3ad5878a561ff904966104a89d91b975967e63a0

**Comment by zx1986** [comment]
I patch it, but still not work.
I am pretty sure the data is UTF-8 in my database.
Because it works fine and show correctly in PHPList.

**Comment by michield** [comment]
Hmm, that's strange. I added a unit test, which passes: https://github.com/michield/phplist-plugin-restapi/blob/master/tests/phpunit/restapi.php#L711

I will try to see how it is when the text is added in phpList and consumed from the API

**Comment by zx1986** [comment]
I'm running in a Docker.
I check my config, and I found my apache startup script:
```
#!/bin/sh
TZ=MET-1METDST
export TZ
exec /usr/sbin/apache2ctl -DNO_DETACH
```

I will remove ```TZ=MET-1METDST``` and test again.

My Dockerfile:
```
FROM phusion/baseimage:0.9.17
CMD ["/sbin/my_init"]

RUN ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
RUN echo "Asia/Taipei" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get update && apt-get install -y \
    apache2 libapache2-mod-php5 \
    php5-cli php5-curl php5-mysql php5-mcrypt php5-json php5-gd php5-mysql php-mail \
    sendmail

# Running additional deamons
RUN mkdir -p /etc/service/httpd/
ADD Dockerconfig/httpd.sh /etc/service/httpd/run
RUN chmod -R 755 /etc/service/

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by zx1986** [comment]
I will try to your testing, and check my env again, then try again.
Thank your for help!

**Comment by zx1986** [comment]
Hello! @michield 
My college found that:
```
--- a/lists/admin/plugins/restapi/includes/pdo.php
+++ b/lists/admin/plugins/restapi/includes/pdo.php
@@ -15,7 +15,7 @@ class PDO extends \PDO
         $dbuser = $GLOBALS['database_user'];
         $dbpass = $GLOBALS['database_password'];
         $dbname = $GLOBALS['database_name'];
-        $dbh = new \PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpass);
+        $dbh = new \PDO("mysql:host=$dbhost;dbname=$dbname", $dbuser, $dbpass, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"));
         $dbh->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
```

And it works.

**Comment by michield** [comment]
great, thanks

**Comment by michield** [comment]
Are you using phpList? Would be cool to update the translation, https://translate.phplist.org/zh_TW/

:hint: :-)

**Comment by michield** [comment]
https://github.com/phpList/phplist-plugin-restapi/pull/24

**Comment by zx1986** [comment]
sure! 
I will do the translate on this weekend :-)
