### ISSUE TITLE
phplist returning 400 bad request?

### ISSUE THREAD

**Issue by lilmike** [phpList/phplist-plugin-restapi#52]
Hi,
I'm running the following command with curl in the terminal, just to test my API:

curl -X post "https://<mysite>/admin/?page=call&pi=restapi" -d "login=<login>&password=<password>&cmd=login"

However, it returns 400 bad request (and returns html). It doesn't return any json, but a webpage saying 400 bad request.
Any thoughts?
-Michael.

**Comment by michield** [comment]
400 errors tend to be permission related. Check your webserver logs. Also, the HTML probably has some info about the error.

**Comment by lilmike** [comment]
Hi,
I solved the 400 error, apparently post is case sensative in curl, so it needed to be -X POST
However, I still have a problem: The returned output is not json, it's html. It looks to me like the admin login page. Again, my url is https://mysite/admin/?page=call&pi=restapi and I'm passing the rest of the parameters with -d in curl, so in the post body. Does this look wrong?
-Michael.
P.S. There's no lists at the beginning intensionally, I setup nginx to have that as the document root and set the URL in phplist accordingly.

**Comment by michield** [comment]
yes, the login is using the normal phpList login, afaict. there's been some work done to change that, but I don't know what state that's in.
