### ISSUE TITLE
Change the GitHub repository description

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist-plugin-restapi#54]
The description should mention that this is the REST plugin for phpList 3.

**Comment by oliverklee** [comment]
@michield Would you be willing to do this? Only an admin for this repository can do this.

**Comment by michield** [comment]
but it already says that? Or am I looking in the wrong place.

**Comment by michield** [comment]
ah, you mean 3, as opposed to phpList without number.

**Comment by michield** [comment]
Ok, done

**Comment by oliverklee** [comment]
Thanks!
